---
- name: ios backup
  block:
    - name: ios backup
      cisco.ios.ios_config:
        backup: yes
      register: config_output
    - name: save variable
      ansible.builtin.set_fact: 
        bup_temp_file: "{{ config_output.backup_path }}"
  when: ansible_network_os == 'ios'

- name: asa backup
  block:
    - name: asa backup
      cisco.asa.asa_config:
        backup: yes
      register: config_output

    - name: save variable
      ansible.builtin.set_fact: 
        bup_temp_file: "{{ config_output.backup_path }}"
  when: ansible_network_os == 'asa'

- name: nxos block with cleanup
  block: 
    - name: nxos backup
      cisco.nxos.nxos_config:
        backup: yes
      register: config_output

    - name: Cleanup time from backup
      ansible.builtin.replace:
        path: "{{ config_output.backup_path }}"
        regexp: '^!Time.*$'
      changed_when: False
      delegate_to: localhost

    - name: Cleanup !Running section from backup
      ansible.builtin.replace:
        path: "{{ config_output.backup_path }}"
        regexp: '^!Running.*$'
      changed_when: False
      delegate_to: localhost

    - name: save variable
      ansible.builtin.set_fact: 
        bup_temp_file: "{{ config_output.backup_path }}"
  when: ansible_network_os == 'nxos'

